# Generated by Django 5.1.7 on 2025-03-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='codinome',
            new_name='nome',
        ),
    ]
