# Generated by Django 5.1.7 on 2025-03-14 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_codinome_url_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='d1',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='d0',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='d1',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, max_length=912, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=192, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to=settings.AUTH_USER_MODEL),
        ),
    ]
