# Generated by Django 5.1.7 on 2025-03-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_grupo_d1_user_d0_user_d1_user_info_user_nome_user_u0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='d1',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='d0',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='d1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
