# Generated by Django 5.1.7 on 2025-03-15 05:51

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_grupo_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='codinome',
            field=models.CharField(max_length=91, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=91),
        ),
        migrations.AlterField(
            model_name='url',
            name='nome',
            field=models.CharField(max_length=91, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=91, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
