# Generated by Django 5.1.7 on 2025-03-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_grupo_codinome_alter_grupo_nome_alter_url_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=119),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=119, null=True),
        ),
    ]
