# Generated by Django 5.1.7 on 2025-03-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_grupo_nome_alter_user_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='codinome',
        ),
    ]
