# Generated by Django 5.1.7 on 2025-03-17 17:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_remove_grupo_codinome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='u0',
        ),
        migrations.AlterField(
            model_name='url',
            name='nome',
            field=models.CharField(max_length=91, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='codinome'),
        ),
    ]
