# Generated by Django 5.1.7 on 2025-03-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_remove_grupo_u0_alter_url_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='grupo público'),
        ),
    ]
