# Generated by Django 5.1.7 on 2025-03-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_grupo_publico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='adm',
            new_name='u0',
        ),
    ]
