# Generated by Django 5.1.7 on 2025-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_rename_adm_grupo_u0'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='sistema',
            field=models.BooleanField(default=False),
        ),
    ]
