# Generated by Django 5.1.7 on 2025-03-27 20:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_user_email_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='convite',
            name='nome',
            field=models.CharField(max_length=119, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='convite',
            name='u0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=119, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
