# Generated by Django 5.1.7 on 2025-03-28 18:54

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_convite_email_alter_convite_nome_alter_convite_u0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=91, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='codinome'),
        ),
    ]
