# Generated by Django 5.1.7 on 2025-04-02 20:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(allow_unicode=True, unique=True)),
                ('publico', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('d1', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=119, validators=[django.core.validators.MinLengthValidator(2)])),
                ('info', models.CharField(blank=True, max_length=912, null=True)),
                ('publico', models.BooleanField(default=False)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('url', models.SlugField(max_length=119)),
                ('etapa', models.IntegerField(choices=[(1, 'Rascunho'), (2, 'Desenvolvimento'), (3, 'Finalizado')], default=3)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='index.grupo')),
                ('u0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(related_name='projetos', to='index.tag')),
            ],
            options={
                'ordering': ['-d1'],
                'abstract': False,
            },
        ),
    ]
