# Generated by Django 5.1.7 on 2025-04-03 18:17

import django.core.validators
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_tag_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.projeto_imagepath),
        ),
        migrations.AddField(
            model_name='projeto',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ano',
            field=models.PositiveSmallIntegerField(blank=True, default=2025, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
