# Generated by Django 5.1.7 on 2025-04-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='tag',
            new_name='tags',
        ),
    ]
