# Generated by Django 5.1.7 on 2025-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_rename_tag_projeto_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='info',
            field=models.CharField(blank=True, max_length=912, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='info',
            field=models.CharField(blank=True, max_length=912, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, max_length=912, null=True, verbose_name='bio'),
        ),
    ]
